version: '3.1'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 17A05A87b
      POSTGRES_USER: AAB-87
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data